<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Surgical Dressing Log</title>
    <style>
        @page { margin: 18px 18px 24px 18px; }
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #111; }
        .header { display: table; width: 100%; margin-bottom: 10px; }
        .header .title { display: table-cell; font-weight: 700; font-size: 14px; }
        .header .date { display: table-cell; text-align: right; font-weight: 700; }
        table { width: 100%; border-collapse: collapse; table-layout: fixed; }
        th, td { border: 1px solid #111; padding: 6px 6px; vertical-align: middle; }
        th { background: #f3f4f6; font-weight: 700; }
        .col-no { width: 6%; text-align: center; }
        .col-id { width: 18%; }
        .col-sex { width: 8%; text-align: center; }
        .col-age { width: 8%; text-align: center; }
        .col-war { width: 7%; text-align: center; }
        .col-lab { width: 7%; text-align: center; }
        .col-burn { width: 7%; text-align: center; }
        .col-notes { width: 39%; }
        .muted { color: #555; font-size: 10px; margin-top: 8px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">Surgical Dressing Log Sheet / OPD</div>
        <div class="date">Date: {{ $titleDate }}</div>
    </div>

    <table>
        <thead>
        <tr>
            <th class="col-no">No</th>
            <th class="col-id">ID NO</th>
            <th class="col-sex">Sex</th>
            <th class="col-age">Age</th>
            <th class="col-war">WW</th>
            <th class="col-lab">Lab</th>
            <th class="col-burn">Burn</th>
            <th class="col-notes">Notes</th>
        </tr>
        </thead>
        <tbody>
        @foreach($patients as $index => $patient)
            <tr>
                <td class="col-no">{{ $index + 1 }}</td>
                <td class="col-id">{{ $patient->id_no }}</td>
                <td class="col-sex">{{ $patient->sex }}</td>
                <td class="col-age">{{ $patient->age }}</td>
                <td class="col-war">{{ $patient->ww ? 'Yes' : 'No' }}</td>
                <td class="col-lab">{{ $patient->lab ? 'Yes' : 'No' }}</td>
                <td class="col-burn">{{ $patient->burn ? 'Yes' : 'No' }}</td>
                <td class="col-notes">{{ $patient->notes }}</td>
            </tr>
        @endforeach

        @for($i = $patients->count(); $i < 30; $i++)
            <tr>
                <td class="col-no">{{ $i + 1 }}</td>
                <td class="col-id">&nbsp;</td>
                <td class="col-sex">&nbsp;</td>
                <td class="col-age">&nbsp;</td>
                <td class="col-war">&nbsp;</td>
                <td class="col-lab">&nbsp;</td>
                <td class="col-burn">&nbsp;</td>
                <td class="col-notes">&nbsp;</td>
            </tr>
        @endfor
        </tbody>
    </table>

    <div class="muted">
        Generated by Surgical Dressing System.
    </div>
</body>
</html>
